openapi: 3.1.0
info:
  title: MMA Gym API
  description: Complete API for managing MMA gym operations including classes, bookings, shop, and user management
  version: 1.0.0
  contact:
    name: Apex MMA
    email: dev@apexmma.com

servers:
  - url: http://localhost:3001/api
    description: Development server
  - url: https://api.apexmma.com
    description: Production server

tags:
  - name: Content
    description: CMS content management
  - name: Classes
    description: Class schedules and templates
  - name: Coaches
    description: Coach profiles and availability
  - name: Auth
    description: Authentication and authorization
  - name: Shop
    description: E-commerce operations
  - name: User
    description: User profile and account management

paths:
  /content/{key}:
    get:
      tags: [Content]
      summary: Get content block by key
      parameters:
        - in: path
          name: key
          required: true
          schema:
            type: string
          example: "home.hero"
        - in: query
          name: locale
          schema:
            type: string
            default: en
      responses:
        '200':
          description: Content block retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'

  /classes/disciplines:
    get:
      tags: [Classes]
      summary: List all martial arts disciplines
      responses:
        '200':
          description: List of disciplines
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ClassDiscipline'

  /classes/sessions:
    get:
      tags: [Classes]
      summary: List class sessions with filters
      parameters:
        - in: query
          name: from
          schema:
            type: string
            format: date-time
        - in: query
          name: to
          schema:
            type: string
            format: date-time
        - in: query
          name: discipline
          schema:
            type: string
        - in: query
          name: coachId
          schema:
            type: string
      responses:
        '200':
          description: List of class sessions
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ClassSession'

  /coaches:
    get:
      tags: [Coaches]
      summary: List all active coaches
      parameters:
        - in: query
          name: specialty
          schema:
            type: string
      responses:
        '200':
          description: List of coaches
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Coach'

  /auth/login:
    post:
      tags: [Auth]
      summary: User authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 6
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                      user:
                        $ref: '#/components/schemas/User'

components:
  schemas:
    ApiResponse:
      type: object
      properties:
        data:
          oneOf:
            - type: object
            - type: array
        meta:
          type: object
          properties:
            page:
              type: integer
            limit:
              type: integer
            total:
              type: integer
            totalPages:
              type: integer

    ClassDiscipline:
      type: object
      required: [id, name, slug]
      properties:
        id:
          type: string
        slug:
          type: string
        name:
          type: string
        description:
          type: string
        tags:
          type: array
          items:
            type: string
        media:
          type: array
          items:
            $ref: '#/components/schemas/MediaItem'

    ClassSession:
      type: object
      required: [id, templateId, coachId, startAt, endAt]
      properties:
        id:
          type: string
        templateId:
          type: string
        coachId:
          type: string
        locationId:
          type: string
        room:
          type: string
        startAt:
          type: string
          format: date-time
        endAt:
          type: string
          format: date-time
        capacity:
          type: integer
          minimum: 1
        bookedCount:
          type: integer
          minimum: 0
        waitlist:
          type: array
          items:
            type: string
        status:
          type: string
          enum: [scheduled, cancelled, full, in_progress, completed]

    Coach:
      type: object
      required: [id, name]
      properties:
        id:
          type: string
        name:
          type: string
        bio:
          type: string
        accolades:
          type: array
          items:
            type: string
        socials:
          type: array
          items:
            $ref: '#/components/schemas/SocialLink'
        photo:
          type: string
          format: uri
        specialties:
          type: array
          items:
            type: string
        hourlyRate:
          type: number
          minimum: 0
        isActive:
          type: boolean

    User:
      type: object
      required: [id, email, name]
      properties:
        id:
          type: string
        email:
          type: string
          format: email
        name:
          type: string
        phone:
          type: string
        roles:
          type: array
          items:
            type: string
            enum: [guest, member, coach, admin]
        credits:
          type: integer
          minimum: 0

    MediaItem:
      type: object
      required: [type, src]
      properties:
        type:
          type: string
          enum: [image, video]
        src:
          type: string
          format: uri
        alt:
          type: string
        caption:
          type: string

    SocialLink:
      type: object
      required: [platform, url]
      properties:
        platform:
          type: string
        url:
          type: string
          format: uri

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []